// ECC Accelerator (SEC-DED) - RTL
// Hardware SEC-DED decoder bridging a UART RX FIFO to the RISC-V core's
// AXI4-Lite bus. It replaces software error correction: each (13,8)
// extended-Hamming frame pulled from the FIFO is decoded by a purely
// combinational syndrome network and the corrected payload is registered
// for AXI readout in the very cycle the frame is popped (zero added
// latency).
//

// Code construction: (13,8) extended Hamming = Hamming(12,8) SEC code
// plus one overall parity bit (SEC-DED).
//
// Frame layout on rx_data[12:0]:
//
//     [12]   [11]   [10]   [9]    [8]    [7:0]
//      P      C3     C2     C1     C0     D7..D0
//
// Hamming bit positions 1..12 (each H-matrix column is the binary value
// of its position; check bits occupy the power-of-two positions):
//
//     pos:  1   2   3   4   5   6   7   8   9   10  11  12
//     bit:  C0  C1  D0  C2  D1  D2  D3  C3  D4  D5  D6  D7
//
// Encoder equations (even parity; this is the contract for the transmit
// side and the testbench):
//     C0 = D0^D1^D3^D4^D6          covers positions {1,3,5,7,9,11}
//     C1 = D0^D2^D3^D5^D6          covers positions {2,3,6,7,10,11}
//     C2 = D1^D2^D3^D7             covers positions {4,5,6,7,12}
//     C3 = D4^D5^D6^D7             covers positions {8,9,10,11,12}
//     P  = ^{C3,C2,C1,C0,D7..D0}   whole 13-bit codeword has even parity
//
// Decoding (standard SEC-DED rule: Hamming syndrome + overall-parity
// enable). The syndrome S is the XOR of each received check bit with the
// check bit recomputed from the received data; because every H column
// equals its position number, S is directly the position (1..12) of a
// single flipped bit, or 0 if the Hamming code sees no error. The
// overall parity of all 13 received bits (parity_fail) is 1 if and only
// if an ODD number of bits flipped:
//
//     S       parity_fail   meaning                        action
//     0       0             no error                       none
//     0       1             P bit itself flipped           payload OK
//     1..12   1             single error at position S     flip that bit
//     1..12   0             double error (any even count)  uncorrectable
//     13..15  1             >= 3 errors (impossible pos.)  uncorrectable
//
// Correction is applied to the payload only; a single error that lands
// in C0..C3 or P leaves the payload untouched and is still reported as
// SINGLE_ERROR_CORRECTED. On uncorrectable frames the raw payload is
// presented as-is and DOUBLE_ERROR_DETECTED tells software to discard it
// (e.g. request retransmission).
//

// FIFO side: first-word fall-through assumed (rx_data shows the oldest
// frame while rx_empty = 0; a one-cycle rx_read_en pulse pops it). A
// frame is popped only while the holding register is free (DATA_READY
// = 0), so unread frames back up inside the FIFO and none are dropped
// here. For a standard-latency FIFO, register rx_read_en into a capture
// strobe one cycle later.
//
// Register map (AXI4-Lite, 32-bit data, byte addresses):
//     0x00  DATA_REG    RO   [7:0] corrected payload
//     0x04  STATUS_REG  RO   [0] DATA_READY
//                            [1] SINGLE_ERROR_CORRECTED
//                            [2] DOUBLE_ERROR_DETECTED (uncorrectable)
//     0x08  CTRL_REG    RW   [0] IRQ_EN
//                            [1] CLEAR_STATUS (write-1 action bit,
//                                self-clearing, reads as 0)
// Writes to the read-only registers are ignored (OKAY response); the
// unmapped offset 0x0C responds with SLVERR (reads return zero).
// Writable bits live in byte lane 0, so only wstrb[0] is honored.
//
// Interrupt: irq = DATA_READY & IRQ_EN, registered, i.e. a glitch-free
// active-high level interrupt for the PLIC. Acknowledge by reading DATA
// and writing CTRL.CLEAR_STATUS = 1.
//
// Fmax notes (Artix-7): each syndrome bit is a single LUT6 (<= 6-input
// XOR); parity_fail is a 13-input XOR (2 LUT levels); each corrected
// payload bit folds {S, parity_fail, D[i]} into one more LUT6. The whole
// decode is ~3 LUT levels deep and feeds registers directly. All AXI
// outputs and irq are registered, and ready/valid are generated by tiny
// registered FSMs - there is no combinational valid->ready path through
// the module.

module ecc_accel #(
  parameter int unsigned AXI_ADDR_WIDTH = 4   // 16-byte register aperture
)(
  input  logic                      clk,
  input  logic                      resetn,

  // UART RX FIFO read interface (first-word fall-through)
  input  logic                      rx_empty,
  output logic                      rx_read_en,
  input  logic [12:0]               rx_data,

  // AXI4-Lite target - write address channel. AxPROT is intentionally
  // omitted on all SoC slaves: the single machine-mode master drives a
  // constant 000 and the interconnect terminates it.
  input  logic [AXI_ADDR_WIDTH-1:0] s_axi_awaddr,
  input  logic                      s_axi_awvalid,
  output logic                      s_axi_awready,

  // AXI4-Lite target - write data channel
  input  logic [31:0]               s_axi_wdata,
  input  logic [3:0]                s_axi_wstrb,
  input  logic                      s_axi_wvalid,
  output logic                      s_axi_wready,

  // AXI4-Lite target - write response channel
  output logic [1:0]                s_axi_bresp,
  output logic                      s_axi_bvalid,
  input  logic                      s_axi_bready,

  // AXI4-Lite target - read address channel
  input  logic [AXI_ADDR_WIDTH-1:0] s_axi_araddr,
  input  logic                      s_axi_arvalid,
  output logic                      s_axi_arready,

  // AXI4-Lite target - read data channel
  output logic [31:0]               s_axi_rdata,
  output logic [1:0]                s_axi_rresp,
  output logic                      s_axi_rvalid,
  input  logic                      s_axi_rready,

  // Level interrupt to the PLIC
  output logic                      irq
);

  // Register word offsets (byte address bits [3:2])
  localparam logic [1:0] REG_DATA     = 2'b00;   // 0x00
  localparam logic [1:0] REG_STATUS   = 2'b01;   // 0x04
  localparam logic [1:0] REG_CTRL     = 2'b10;   // 0x08
  localparam logic [1:0] REG_UNMAPPED = 2'b11;   // 0x0C

  // AXI4-Lite responses
  localparam logic [1:0] RESP_OKAY   = 2'b00;
  localparam logic [1:0] RESP_SLVERR = 2'b10;

  
  //  Combinational SEC-DED decoder
  
  logic [7:0] rx_payload;
  logic [3:0] rx_check;

  assign rx_payload = rx_data[7:0];
  assign rx_check   = rx_data[11:8];

  
  // Syndrome computation: XOR each received check bit with the check
  // bit recomputed from the received payload. Each equation has at most
  // 6 terms, so each syndrome bit maps to exactly one Artix-7 LUT6.
  
  logic [3:0] syndrome;

  assign syndrome[0] = rx_check[0] ^ rx_payload[0] ^ rx_payload[1] ^ rx_payload[3]
                                   ^ rx_payload[4] ^ rx_payload[6];
  assign syndrome[1] = rx_check[1] ^ rx_payload[0] ^ rx_payload[2] ^ rx_payload[3]
                                   ^ rx_payload[5] ^ rx_payload[6];
  assign syndrome[2] = rx_check[2] ^ rx_payload[1] ^ rx_payload[2] ^ rx_payload[3]
                                   ^ rx_payload[7];
  assign syndrome[3] = rx_check[3] ^ rx_payload[4] ^ rx_payload[5] ^ rx_payload[6]
                                   ^ rx_payload[7];

  // Overall parity of the received 13-bit word. A clean codeword has
  // even parity, so parity_fail = 1 <=> an odd number of bits flipped.
  // This is the "enable" of the correction stage: with at most two
  // errors assumed, odd parity means exactly one error (correctable)
  // and even parity with a non-zero syndrome means two (uncorrectable).
  logic parity_fail;
  assign parity_fail = ^rx_data;

  
  // Syndrome decode: one-hot flip vector for the payload bits. The
  // comparison constant of each line is the Hamming position the data
  // bit occupies (see the position table in the header). Syndromes that
  // point at check bits (1,2,4,8), at the parity bit (S=0 with
  // parity_fail=1), or at impossible positions (13..15) naturally match
  // no entry, so the payload is left untouched in those cases.
  
  logic [7:0] flip;

  assign flip[0] = (syndrome == 4'd3);    // D0 sits at Hamming position 3
  assign flip[1] = (syndrome == 4'd5);    // D1 -> position 5
  assign flip[2] = (syndrome == 4'd6);    // D2 -> position 6
  assign flip[3] = (syndrome == 4'd7);    // D3 -> position 7
  assign flip[4] = (syndrome == 4'd9);    // D4 -> position 9
  assign flip[5] = (syndrome == 4'd10);   // D5 -> position 10
  assign flip[6] = (syndrome == 4'd11);   // D6 -> position 11
  assign flip[7] = (syndrome == 4'd12);   // D7 -> position 12

  // Correction is gated by parity_fail: on a double error (parity even)
  // the non-zero syndrome points at an INNOCENT bit, so flipping it
  // would add a third error - the gate prevents exactly that. Per bit
  // this folds into one LUT6: {S[3:0], parity_fail, D[i]} -> 6 inputs.
  logic [7:0] corrected_payload;
  assign corrected_payload = rx_payload ^ (flip & {8{parity_fail}});

  
  // Frame classification (see the decode table in the header)
  
  logic syndrome_nonzero;
  logic syndrome_invalid;

  assign syndrome_nonzero = |syndrome;
  // Positions 13..15 do not exist in a 12-bit Hamming codeword; a single
  // error can never produce them, so they imply at least 3 raw errors.
  assign syndrome_invalid = (syndrome > 4'd12);

  logic frame_corrected;       // exactly one (odd) error, repaired
  logic frame_uncorrectable;   // detected but beyond SEC capability

  assign frame_corrected     = parity_fail & ~syndrome_invalid;
  assign frame_uncorrectable = (syndrome_nonzero & ~parity_fail)   // even count >= 2
                             | (parity_fail & syndrome_invalid);   // odd count >= 3

  
  //  FIFO pull engine + holding registers
  
  logic [7:0] data_reg;     // DATA_REG   [7:0]
  logic       data_ready;   // STATUS_REG [0]
  logic       st_single;    // STATUS_REG [1]
  logic       st_double;    // STATUS_REG [2]
  logic       irq_en;       // CTRL_REG   [0]

  // CTRL write strobes (defined with the write FSM below)
  logic ctrl_wr_en;
  logic ctrl_clear_strobe;

  
  // Pop a frame only while the holding register is free. rx_read_en is
  // registered: a clean one-cycle strobe with no combinational path
  // from rx_empty back into the FIFO. The ~rx_read_en term blocks a
  // back-to-back double pop (data_ready updates only at the same edge
  // the pop completes, so it cannot gate the very next cycle itself).
  
  always_ff @(posedge clk or negedge resetn) begin
    if (!resetn)
      rx_read_en <= 1'b0;
    else
      rx_read_en <= ~rx_empty & ~data_ready & ~rx_read_en;
  end

  
  // Capture: during the pop cycle the FWFT FIFO still presents the
  // frame on rx_data, so the combinational decode result is valid and
  // is registered at the same edge that retires the frame.
  
  always_ff @(posedge clk or negedge resetn) begin
    if (!resetn) begin
      data_reg   <= 8'h00;
      data_ready <= 1'b0;
      st_single  <= 1'b0;
      st_double  <= 1'b0;
    end
    else begin
      // Software acknowledge via CTRL.CLEAR_STATUS
      if (ctrl_clear_strobe) begin
        data_ready <= 1'b0;
        st_single  <= 1'b0;
        st_double  <= 1'b0;
      end

      // New-frame capture. Listed after the clear so that a frame
      // landing in the same cycle as an acknowledge is never lost
      // (capture wins). In normal operation they cannot collide since
      // pops are issued only while data_ready = 0.
      if (rx_read_en) begin
        data_reg   <= corrected_payload;
        st_single  <= frame_corrected;
        st_double  <= frame_uncorrectable;
        data_ready <= 1'b1;
      end
    end
  end

  // Registered level interrupt: glitch-free input for the PLIC
  always_ff @(posedge clk or negedge resetn) begin
    if (!resetn)
      irq <= 1'b0;
    else
      irq <= data_ready & irq_en;
  end

  
  //  AXI4-Lite write channel (AW + W -> B)
  
  typedef enum logic [1:0] {
    WR_IDLE = 2'b00,
    WR_XFER = 2'b01,
    WR_RESP = 2'b10
  } wr_state_t;

  wr_state_t wr_state;

  logic [1:0] wr_sel;
  assign wr_sel = s_axi_awaddr[3:2];

  // CTRL register write decode. Strobes are valid only during WR_XFER,
  // the single cycle in which both AW and W handshakes complete and the
  // master is still holding address and data on the bus.
  assign ctrl_wr_en        = (wr_state == WR_XFER) && (wr_sel == REG_CTRL) && s_axi_wstrb[0];
  assign ctrl_clear_strobe = ctrl_wr_en && s_axi_wdata[1];

  always_ff @(posedge clk or negedge resetn) begin
    if (!resetn) begin
      wr_state      <= WR_IDLE;
      s_axi_awready <= 1'b0;
      s_axi_wready  <= 1'b0;
      s_axi_bvalid  <= 1'b0;
      s_axi_bresp   <= RESP_OKAY;
      irq_en        <= 1'b0;   // Interrupts disabled out of reset
    end
    else begin
      case (wr_state)
        WR_IDLE: begin
          // A slave may legally wait until BOTH the address and the data
          // beats are offered before asserting the ready pair; doing so
          // keeps the FSM minimal and the readys registered.
          if (s_axi_awvalid && s_axi_wvalid) begin
            s_axi_awready <= 1'b1;
            s_axi_wready  <= 1'b1;
            wr_state      <= WR_XFER;
          end
        end

        WR_XFER: begin
          // Both handshakes complete at the end of this cycle. Commit
          // the write side effects here. DATA_REG / STATUS_REG are
          // read-only: writes to them are silently ignored (OKAY).
          s_axi_awready <= 1'b0;
          s_axi_wready  <= 1'b0;
          if (ctrl_wr_en)
            irq_en <= s_axi_wdata[0];
          s_axi_bresp  <= (wr_sel == REG_UNMAPPED) ? RESP_SLVERR : RESP_OKAY;
          s_axi_bvalid <= 1'b1;
          wr_state     <= WR_RESP;
        end

        WR_RESP: begin
          if (s_axi_bready) begin
            s_axi_bvalid <= 1'b0;
            wr_state     <= WR_IDLE;
          end
        end

        default: wr_state <= WR_IDLE;
      endcase
    end
  end

  
  //  AXI4-Lite read channel (AR -> R)
  
  typedef enum logic [1:0] {
    RD_IDLE = 2'b00,
    RD_XFER = 2'b01,
    RD_RESP = 2'b10
  } rd_state_t;

  rd_state_t rd_state;

  logic [1:0] rd_sel;
  assign rd_sel = s_axi_araddr[3:2];

  always_ff @(posedge clk or negedge resetn) begin
    if (!resetn) begin
      rd_state      <= RD_IDLE;
      s_axi_arready <= 1'b0;
      s_axi_rvalid  <= 1'b0;
      s_axi_rresp   <= RESP_OKAY;
      s_axi_rdata   <= '0;
    end
    else begin
      case (rd_state)
        RD_IDLE: begin
          if (s_axi_arvalid) begin
            s_axi_arready <= 1'b1;
            rd_state      <= RD_XFER;
          end
        end

        RD_XFER: begin
          // AR handshake completes at the end of this cycle; the master
          // is still driving a stable ARADDR, so the register mux can
          // be sampled directly into the registered RDATA.
          s_axi_arready <= 1'b0;
          case (rd_sel)
            REG_DATA:   s_axi_rdata <= {24'b0, data_reg};
            REG_STATUS: s_axi_rdata <= {29'b0, st_double, st_single, data_ready};
            REG_CTRL:   s_axi_rdata <= {30'b0, 1'b0, irq_en};  // CLEAR_STATUS reads as 0
            default:    s_axi_rdata <= 32'b0;
          endcase
          s_axi_rresp  <= (rd_sel == REG_UNMAPPED) ? RESP_SLVERR : RESP_OKAY;
          s_axi_rvalid <= 1'b1;
          rd_state     <= RD_RESP;
        end

        RD_RESP: begin
          if (s_axi_rready) begin
            s_axi_rvalid <= 1'b0;
            rd_state     <= RD_IDLE;
          end
        end

        default: rd_state <= RD_IDLE;
      endcase
    end
  end

  // Explicit sink for intentionally unused inputs (write strobes above
  // byte lane 0, sub-word address bits) to keep simulators and linters
  // quiet. Synthesis still notes these bits as load-free - expected for
  // a byte-addressed AXI slave whose registers live in byte lane 0.
  wire _unused_inputs;
  assign _unused_inputs = &{1'b0, s_axi_wstrb[3:1],
                            s_axi_awaddr[1:0], s_axi_araddr[1:0]};

endmodule
